<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE note [
<!ELEMENT note (to, from, heading, (|image), footer?)> 
<!ELEMENT to (#PCDATA)> 
<!ELEMENT from (#PCDATA)>
<!ELEMENT heading (#PCDATA)> 
<!ELEMENT footer (#PCDATA)>
<!ELEMENT body (#PCDATA)>
<!ELEMENT iamge (#PCDATA)>
<!ATTLIST bodY color ID #IMPLIED>
<!ATTLIST body saludo (hola | hi | konichiwa) "hola">
<!ENTITY nbsp "&#xA0;">
<!ENTITY writer "Writer: Donald Duck."> 
<!ENTITY copyright "Copyright: W3Schools.">
]>
<note>
<to>Tove</to>
<from>Jani</from>
<heading>Reminder</heading>
<body saludo="hola">xxx</body>
</note>