=== dana044/40260/xml/xml-00.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT direccion (nombreCompleto, correo, telefono, cumple)>
<!ELEMENT nombreCompleto (nombre, apellidos)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT apellidos (#PCDATA)>
<!ELEMENT correo (#PCDATA)>
<!ELEMENT telefono (#PCDATA)>
<!ELEMENT cumple (dia, mes, anio)>
<!ELEMENT dia (#PCDATA)>
<!ELEMENT mes (#PCDATA)>
<!ELEMENT anio (#PCDATA)>

=== dana044/40260/xml/xml-00.xml
<?xml version="1.0" encoding="URF-8"?>
<!DOCTYPE direccion SYSTEM "xml-00.dtd">
<direccion>
    <nombreCompleto>
        <nombre>Citlaly</nombre>
        <apellidos>Morales Viveros</apellidos>
    </nombreCompleto>

    <correo>citlipop@gmail.com</correo>
    <telefono>2282782080</telefono>

    <cumple>
        <dia>15</dia>
        <mes>10</mes>
        <anio>2006</anio>
    </cumple>
</direccion>
